site_name: Echo Speaks Documentation
site_url: https://tonesto7.github.io/echo-speaks-docs
repo_url: https://github.com/tonesto7/echo-speaks
edit_uri: ""
site_description: Echo Speaks Documentation
# use_directory_urls: False
remote_branch: gh-pages
remote_name: origin
google_analytics: ["UA-131811674-1", "tonesto7.github.io/echo-speaks-docs"]

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.top
    - toc.integrate
  hide:
    - toc
  favicon: /img/favicon.png
  logo: /img/EchoSpeaks.png


  extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/tonesto7/echo-speaks
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    primary: "blue"
    accent: "blue"

nav:
  - Home: index.md

  - Install:
    - Automated:
      - Hubitat Package Manager: hubitat/installation/hpm_install.md

    - Manual:
      - App Install: hubitat/installation/app_install.md
      - Driver Install: hubitat/installation/device_install.md

  - Configuration:
    - App Configuration: hubitat/configuration/config_app.md
    - Server Configuration: hubitat/configuration/config_server.md

  - Updates:
    - App Updates: hubitat/updates/app_update.md
    - Device Updates: hubitat/updates/device_update.md
    - Server Updates: hubitat/updates/server_update.md

  - Actions:
      - Description: actions/actions_desc.md
      - Configuration: actions/config/actions_config.md
      - Examples: actions/examples/actions_examples.md

  - Support:
      - Server Removal/Reset: support/server_removal.md
      - Common Errors: support/common_errors.md
      - Reporting Issues: support/reporting_issues.md
      - F.A.Q.: faq.md

  - Device API:
      - Device Attributes: devicesupport/device_attributes.md
      - Device Commands:
          - General: devicesupport/commands/action_commands.md
          - Alerts | Notifications: devicesupport/commands/alerts_commands.md
          - Music: devicesupport/commands/music_commands.md
          - Speech: devicesupport/commands/speech_commands.md
  - Donations:
      - Paypal: donations.md

markdown_extensions:
  - admonition
  - smarty:
      smart_quotes: false
  - meta
  - sane_lists
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - codehilite
  # - admonition
  # - superfences
  #   highlight_code: True
  #   disable_indented_code_blocks: False
  #   preserve_tabs: True
  #   linenums: True
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True

plugins:
  - search:
      prebuild_index: true
  - autolinks
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  # - mdoctag
  # - bootstrap-tables

extra_css:
  - "css/extra.css"
  - "css/monokai.css"

extra_javascript:
  - "js/extra.js"
