site_name: Echo Speaks Documentation
site_url: https://tonesto7.github.io/echo-speaks-docs/
repo_url: https://github.com/tonesto7/echo-speaks-docs
site_description: Echo Speaks Documentation
# use_directory_urls: False
remote_branch: gh-pages
remote_name: origin
google_analytics:
  - "UA-131811674-1"
  - "tonesto7.github.io/echo-speaks-docs"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
  hide:
    - toc
  font:
    text: Roboto
  # favicon: img/favicon.png
  logo: img/EchoSpeaks.png
  # extra:
  #   social:
  #     - icon: fontawesome/brands/github
  #       link: https://github.com/tonesto7/echo-speaks
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    primary: "blue"
    accent: "blue"
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

nav:
  - Home: index.md

  - Install:
    - Install Types: installation/types.md

    - Automated:
      - Hubitat Package Manager: installation/hpm_install.md

    - Manual:
      - App Install: installation/app_install.md
      - Driver Install: installation/device_install.md

  - Configuration:
    - App Configuration: configuration/config_app.md
    - Server Configuration: configuration/config_server.md

  - Updates:
    - App Updates: updates/app_update.md
    - Device Updates: updates/device_update.md
    - Server Updates: updates/server_update.md

  - Actions:
      - Description: actions/actions_desc.md
      - Configuration: actions/config/actions_config.md
      - Examples: actions/examples/actions_examples.md

  - Support:
      - Server Removal/Reset:
        - Server Removal/Reset: support/server_removal.md
      - Common Errors:
        - Common Errors: support/common_errors.md
      - Reporting Issues:
        - Issue Reporting: support/reporting_issues.md
      - F.A.Q.:
        - Questions: faq.md

  - Device API:
      - Supported Devices:
        - Devices: devicesupport/supported_devices.md
      - Device Attributes:
        - Attributes: devicesupport/device_attributes.md
      - Device Commands:
          - General: devicesupport/commands/action_commands.md
          - Alerts | Notifications: devicesupport/commands/alerts_commands.md
          - Music: devicesupport/commands/music_commands.md
          - Speech: devicesupport/commands/speech_commands.md

  - Donations:
      - Paypal: donations.md

  - GitHub:
      - Code Repository: github_repo.md

markdown_extensions:
  - attr_list
  - admonition
  - smarty:
      smart_quotes: false
  - meta
  - sane_lists
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - codehilite

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.pathconverter
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed

  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True

plugins:
  - search:
      prebuild_index: true
  - autolinks
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  # - mdoctag
  # - bootstrap-tables

extra_css:
  - "css/extra.css"
  - "css/monokai.css"
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

extra_javascript:
  - "js/extra.js"
  - "js/config.js"
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
